version: '3.8'

services:
  # Grafana - 데이터 시각화
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - k6-lgtm-network
    depends_on:
      - prometheus
      - loki
      - tempo

  # Prometheus - 메트릭 저장
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - k6-lgtm-network

  # Loki - 로그 수집 및 저장
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - k6-lgtm-network

  # Tempo - 분산 트레이싱
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo-config.yml"]
    ports:
      - "3200:3200"
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./config/tempo:/etc/tempo
    networks:
      - k6-lgtm-network

  # k6 - 부하 테스트 도구
  k6:
    image: grafana/k6:latest
    container_name: k6
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_LOKI_ADDR=http://loki:3100
      - K6_TEMPO_URL=http://tempo:4317
    volumes:
      - ../../scripts/k6:/scripts
    networks:
      - k6-lgtm-network
    depends_on:
      - prometheus
      - loki
      - tempo

  # k6-operator - Kubernetes integration (optional)
  # k6-operator:
  #   image: grafana/k6-operator:latest
  #   container_name: k6-operator
  #   networks:
  #     - k6-lgtm-network
  #   depends_on:
  #     - k6

networks:
  k6-lgtm-network:
    driver: bridge

volumes:
  prometheus_data: {} 