services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=application
      - SPRING_DATASOURCE_PASSWORD=application
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_TIMEOUT=3000
      - SPRING_REDIS_CONNECT_TIMEOUT=3000
    volumes:
      - ./logs:/var/log
    depends_on:
      - mysql 