services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./load-tests:/tests
    environment:
      - K6_INFLUXDB_USERNAME=k6
      - K6_INFLUXDB_DB=k6
      - K6_INFLUXDB_ADDR=http://influxdb:8086
      - K6_INFLUXDB_PASSWORD=k6password
      - K6_INFLUXDB_INSECURE=true
      - API_HOST=app:8080
      - RUN_TEST=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=hhplus
      - DB_USER=application
      - DB_PASSWORD=application
    depends_on:
      - influxdb
      - app
      - mysql
    entrypoint: ["k6", "run"]
    command: >
      --out influxdb=${K6_INFLUXDB_ADDR:-http://influxdb:8086}/${K6_INFLUXDB_DB:-k6}
      /tests/${K6_SCRIPT:-load-test.js}
    networks:
      - default
      - monitoring

networks:
  default:
    name: voyage-shop_default
    external: false
  monitoring:
    name: voyage-shop_monitoring
    external: false
    
