services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-compose
    volumes:
      - ./logs:/var/log
    depends_on:
      - mysql 
      - redis
    networks:
      - default
      - monitoring

networks:
  default:
    driver: bridge
  monitoring:
    name: voyage-shop_monitoring
    external: false 