apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  # base64로 인코딩된 값: root, application
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: YXBwbGljYXRpb24= 