apiVersion: 1

datasources:
  - id: P951FEA4DE68E13C5
    name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: k6
    secureJsonData:
      password: k6password
    jsonData:
      httpMode: GET
      timeInterval: 5s 