name: 🛠️ 기술적 개선
description: 백엔드 API의 리팩토링, 성능 개선, 기술 부채 해소 등 기술적 개선을 제안합니다
title: "[TECH] "
labels: ["technical", "improvement"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: 🏷️ 우선순위
      description: 이슈의 우선순위를 선택해주세요
      options:
        - 높음 (시급한 문제 또는 핵심 시스템에 영향)
        - 중간 (중요하지만 당장 해결하지 않아도 됨)
        - 낮음 (여유 있을 때 해결해도 됨)
        - 백로그 (향후 고려할 작업, 현재 스프린트에는 포함되지 않음)
    validations:
      required: true

  - type: textarea
    id: priority-reason
    attributes:
      label: 우선순위 설명
      description: 선택한 우선순위의 이유를 간략히 설명해주세요
    validations:
      required: false

  - type: checkboxes
    id: improvement-type
    attributes:
      label: 📝 개선 유형
      description: 어떤 유형의 기술적 개선인지 선택해주세요
      options:
        - label: 코드 리팩토링 (가독성, 유지보수성 향상)
        - label: 아키텍처 개선 (설계 패턴, 구조 변경)
        - label: 성능 최적화 (API 응답 시간, DB 쿼리 개선)
        - label: 기술 부채 해소 (레거시 코드, 종속성 업데이트)
        - label: 데이터베이스 최적화 (인덱스, 스키마 개선)
        - label: 보안 강화 (취약점 해결, 인증/권한 개선)
        - label: 테스트 개선 (테스트 커버리지, 테스트 품질)
        - label: 로깅/모니터링 개선 (오류 추적, 성능 모니터링)
        - label: CI/CD 파이프라인 개선
        - label: 기타 (아래에 설명해주세요)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 📝 개선 요약
      description: 제안하는 기술적 개선 사항에 대해 간결하게 설명해주세요
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: 🔄 현재 상황
      description: 현재 코드/아키텍처의 문제점이나 개선이 필요한 부분을 상세히 설명해주세요
      placeholder: |
        ### 문제점
        (현재 코드/API의 구체적인 문제점은 무엇인가요?)

        ### 영향 범위
        (이 문제가 영향을 미치는 API/서비스 범위는 어디까지인가요?)
        
        ### 기술적 부채
        (현재 구현이 향후 개발에 어떤 제약을 주고 있나요?)
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: 💡 제안하는 개선 방법
      description: 어떻게 개선할 것인지 상세히 설명해주세요
      placeholder: |
        ### 접근 방식
        (어떤 접근 방식으로 문제를 해결할 것인지 설명해주세요)

        ### 기술적 세부사항
        (구체적인 기술, 패턴, 알고리즘, 라이브러리 등을 설명해주세요)
        
        ```kotlin
        // 코드 예시
        ```

        ### 대안 검토
        (고려한 다른 대안들과 이 방법을 선택한 이유를 설명해주세요)
    validations:
      required: true

  - type: textarea
    id: expected-effects
    attributes:
      label: 📊 예상되는 효과
      description: 이 개선으로 인해 기대되는 효과를 설명해주세요
      placeholder: |
        ### 정량적 효과
        (측정 가능한 효과를 숫자로 표현해주세요)
        - API 응답 시간 x% 단축
        - DB 쿼리 실행 시간 x% 감소
        - 메모리 사용량 x% 감소

        ### 정성적 효과
        (코드 품질, 유지보수성, 확장성 등 정성적인 효과를 설명해주세요)
    validations:
      required: true

  - type: textarea
    id: verification-method
    attributes:
      label: 🧪 검증 방법
      description: 개선 후 효과를 어떻게 측정하고 검증할 것인지 설명해주세요
      placeholder: |
        ### 테스트 시나리오
        (성공을 검증할 테스트 시나리오를 작성해주세요)
        
        ### 측정 지표
        (성능 개선을 측정할 구체적인 지표나 방법을 설명해주세요)
        - 응답 시간 측정 방법
        - 리소스 사용량 측정 방법
    validations:
      required: true

  - type: textarea
    id: related-code
    attributes:
      label: 📋 관련 코드/파일
      description: 변경이 필요한 주요 코드나 파일 위치를 나열해주세요
      placeholder: |
        - `src/main/kotlin/kr/hhplus/be/server/domain/order/OrderService.kt`
        - `src/main/kotlin/kr/hhplus/be/server/infrastructure/repository/OrderRepository.kt`
    validations:
      required: false

  - type: textarea
    id: estimated-time
    attributes:
      label: 📆 예상 일정
      description: 이 작업을 완료하는데 예상되는 시간을 적어주세요
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 📚 참고 자료
      description: 이 개선과 관련된 참고 자료, 문서, 링크 등을 제공해주세요
    validations:
      required: false 