apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voyage-shop-mysql.fullname" . }}-config
  labels:
    app: {{ .Values.mysql.name }}
    {{- include "voyage-shop-mysql.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.config.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.mysql.config.MYSQL_USER }} 