apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.name }}
    {{- include "voyage-shop-mysql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
        {{- include "voyage-shop-mysql.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.config.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.config.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.config.MYSQL_PASSWORD }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.config.MYSQL_ROOT_PASSWORD }}
          args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          volumeMounts:
            - name: mysql-emptydir
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-emptydir
          emptyDir: {} 