apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voyage-shop-mysql.fullname" . }}-secret
  labels:
    app: {{ .Values.mysql.name }}
    {{- include "voyage-shop-mysql.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.config.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.config.MYSQL_PASSWORD | b64enc }} 