global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Exemplars 설정 추가
# Tempo로부터 트레이스 ID를 가져오기 위한 설정
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    # Exemplar 설정 추가
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'spring-boot-app'
    # Exemplar 관련 설정
    honor_labels: true
    metric_relabel_configs:
      - source_labels: ["__name__"]
        regex: ".*_seconds(?:_bucket|_count|_sum)$"
        action: keep 