apiVersion: 1

datasources:
  - uid: influxdb0001
    name: InfluxDB-k6
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: k6password
    user: k6
    isDefault: false

  - uid: loki000000001
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    
  - uid: tempo00000001
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    
  - uid: prom000000001
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true