apiVersion: 1

datasources:
  - id: P951FEA4DE68E13C5
    name: InfluxDB-k6
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: k6password
    user: k6
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: false 
    
  - name: AppMetrics
    type: prometheus
    access: proxy
    url: http://app:8080/actuator/prometheus
    isDefault: false
    editable: true 